### ISSUE TITLE
Agenda Präsentation Studienarbeit

### ISSUE THREAD

**Issue by RobinBaumann** [RobinBaumann/InformatiCup2018#42]
- Übersicht /Aufgabenstellung (Tom)
- Fixed Path Gas Station Problem (Tom)
- Prediction Model (Robin)
- Implementierung, Anwendungsszenario (Carlo)
- Live Demo
- Weiterführende Literatur

**Comment by c-goetz** [comment]
sollen wir das evtl. überarbeiten?

Freudis money-quote:

> Ziel der Veranstaltung ist es,
> Außenstehenden, Dozenten und Ihren Kommilitonen - insbesondere aus den
> nachfolgenden Jahrgängen - zu zeigen, was für tolle und interessante
> Sachen man in der Studienarbeit machen kann. Richten Sie Ihren Vortrag also
> nach diesem Ziel aus. Beschreiben Sie die besonderen Herausforderungen.

**Comment by anon767** [comment]
hm was haltet ihr davon?

- Übersicht /Aufgabenstellung (Tom)
- nur kurz Prediction Model (Robin)
- Anwendungsszenario (Carlo)
- Live Demo (gemeinsam)
- Weiterführende Literatur (villt nur als Folie? ich mein wen interessierts)
